# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-reproducibility-nix

# Trigger the workflow when:
on:
  push:
    branches:
      - main
      - stable/*
      - nix-flake*
  # Besides pushes on the branches above, also check every day at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"

jobs:

  check-reproducible-build:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/9a3cfff2f9035ca0bd54ff13b608c4492eca6be3.tar.gz
      - run: nix --version
      - run: nix build .#nosgx
      - run: shasum -a 512256 -b result/bin/cipher-paratime

      - name: Shasum check
        run: |
          echo "d4c77a86e0d1502313d70095f3badcd5a1499510f8131b0665dd2a93dbfd00b2 *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check

  check-reproducible-build-sgx:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-sgx-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/9a3cfff2f9035ca0bd54ff13b608c4492eca6be3.tar.gz
      - run: nix --version
      - run: nix build .#sgx
      - run: shasum -a 512256 -b result/bin/cipher-paratime.sgxs

      - name: Shasum check
        run: |
          echo "547c506aee7c7ee53e85ce0842e840010979288c8350a0b9dc1d510d8b431abf *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check
