# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: nix-build

# Trigger the workflow when:
on:
  push:
    branches:
      - main
      - stable/*
      - nix*

  pull_request:
    branches:
      - main
      - stable/*
      - nix*

  # Besides pushes on the branches above, also check every day at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"

jobs:

  check-reproducible-build:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220225_fd4b693/install

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix --version
      - run: nix build .#nosgx
      - run: shasum -a 512256 -b result/bin/cipher-paratime
      - run: sha256sum result/bin/cipher-paratime

      - name: Shasum check
        run: |
          # FIXME shasum of local build does not match the one on github ci
          #       perhaps some dependencies are not pinned
          echo "71d0976294bda711ead42bc42e57d3fac7cdb2dab11d62c2734abad08ae425da *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check

      - run: nix build --rebuild .#nosgx

      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result

  check-reproducible-build-sgx:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-sgx-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220225_fd4b693/install

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix --version
      - run: nix build .#sgx
      - run: shasum -a 512256 -b result/bin/cipher-paratime.sgxs
      - run: sha256sum result/bin/cipher-paratime.sgxs

      - name: Shasum check
        run: |
          # FIXME shasum of local build does not match the one on github ci
          #       perhaps some dependencies are not pinned
          echo "fbd36bb70d0e381866a3aa0da5e52304c16dc022b86e44302b18e104aecc2743 *result/bin/cipher-paratime.sgxs" | shasum --algorithm 512256 --binary --strict --check

      - run: nix build --rebuild .#sgx

      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result
