# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: nix-in-docker

# Trigger the workflow when:
on:
  push:
    branches:
      - main
      - stable/*
      - nix*
  pull_request:
    branches: [ main, nix ]

  # Besides pushes on the branches above, also check every day at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  check-reproducible-build:
    # NOTE: This name appears in GitHub's Checks API.
    name: nix-in-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
          docker run --rm -v $PWD:/src -w /src nixpkgs/nix-flakes /bin/bash -c "nix build .#nosgx && sha256sum result/bin/cipher-paratime && cp result/bin/cipher-paratime ."

      - run: shasum -a 512256 -b cipher-paratime
      - run: sha256sum cipher-paratime

      - name: Sha256sum check
        run: |
          #echo "6e7f332b7726db2d721467fa5743cda30168602b8075a539821701b085d8fb42 *cipher-paratime" | sha256sum --strict --check
          echo "890201e036a5edf1e75c184752e8f17b096ec83bba11aa30257b52cf726688dd *cipher-paratime" | sha256sum --strict --check
