# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: nix-build

# Trigger the workflow when:
on:
  push:
    branches:
      - main
      - stable/*
      - nix*

  pull_request:
    branches:
      - main
      - stable/*
      - nix*

  # Besides pushes on the branches above, also check every day at 00:00 UTC.
  schedule:
    - cron: "0 0 * * *"

jobs:

  check-reproducible-build:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220225_fd4b693/install

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: echo "number of cores: $(nproc)"
      - run: nix --version
      - run: nix build .#nosgx
      - run: sha256sum result/bin/cipher-paratime
      - run: shasum -a 512256 -b result/bin/cipher-paratime

      - name: sha256sum check
        run: |
          echo "0d97d71f78c0886515192c871a0411896a881d6cf220de9c1aca8d6253afe08b *result/bin/cipher-paratime" | sha256sum --strict --check

      - name: shasum check
        run: |
          # FIXME shasum of local build does not match the one on github ci
          #       perhaps some dependencies are not pinned
          #echo "d4c77a86e0d1502313d70095f3badcd5a1499510f8131b0665dd2a93dbfd00b2 *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check
          #echo "b0c2e27d8b09e3d0337e65c3bac04f33b68afa16a09ccd3189cf039f222db7de *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check
          echo "4e7343d5d7da626f8da99ce26afe1c4302f14e45c9914746008bdd2a6811ccdd *result/bin/cipher-paratime" | shasum --algorithm 512256 --binary --strict --check

      - run: nix build --rebuild .#nosgx

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: artifact_cipher-paratime_${{ github.ref_name }}
          path: result/bin/cipher-paratime

      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result

  check-reproducible-build-sgx:
    # NOTE: This name appears in GitHub's Checks API.
    name: check-reproducibility-sgx-with-nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220225_fd4b693/install

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: echo "number of cores: $(nproc)"
      - run: nix --version
      - run: nix build .#sgx

      - run: sha256sum result/bin/cipher-paratime.sgxs
      - name: sha256sum check
        run: |
          # f7ff2296f5182cb287a30cab7c41a8a2ab75e72847300b9131f1507e37826322
          echo "953d2245b48a97d4c6f024d8e82be1b14189b47b7c06feb1328e5a5cfbf40c60 *result/bin/cipher-paratime.sgxs" | sha256sum --strict --check

      - run: shasum -a 512256 -b result/bin/cipher-paratime.sgxs
      - name: shasum 512256 check
        run: |
          # FIXME shasum of local build does not match the one on github ci
          #       perhaps some dependencies are not pinned
          #echo "547c506aee7c7ee53e85ce0842e840010979288c8350a0b9dc1d510d8b431abf *result/bin/cipher-paratime.sgxs" | shasum --algorithm 512256 --binary --strict --check
          #echo "fbd36bb70d0e381866a3aa0da5e52304c16dc022b86e44302b18e104aecc2743 *result/bin/cipher-paratime.sgxs" | shasum --algorithm 512256 --binary --strict --check
          echo "f3fd91db7e13a33af391e854f961c2a4f3db5609be78ab87cd884a26aa105c7c *result/bin/cipher-paratime.sgxs" | shasum --algorithm 512256 --binary --strict --check

      - run: nix build --rebuild .#sgx

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: artifact_cipher-paratime-sgx_${{ github.ref_name }}
          path: result/bin/cipher-paratime.sgxs

      - run: nix flake check
      - run: nix flake metadata
      - run: nix flake show
      - run: ls -l result
